<a href="https://colab.research.google.com/github/prasannashrestha011/NeuralNetworkFromScratch/blob/main/SimpleNeuralNetwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
inputs = [0.1, -0.5, 0.6, 0.9]
weights = [
    [1.1, 0.3, 0.4, 1.2],
    [1.2, 0.4, 0.8, 1.5],
    [-0.2, 0.4, 0.9, -1.2],
]
biases = [1, 2, 3]
baises=[1,2,3]
layers_outputs=[]
for neuron_weights,baise in zip(weights,baises):
    neuron_output=0
    for x,w in zip(inputs,neuron_weights):
        neuron_output+=x*w
    neuron_output+=baise
    layers_outputs.append(neuron_output)
print(neuron_output)




2.24


In [71]:
import numpy as np

np.random.seed(0)
X=np.random.rand(4,3) # 4 samples containing 3 features

class Dense_Layer:
    def __init__(self,n_inputs,n_neurons) -> None:
      #we initialize the weights using n_inputs and n_neurons
        self.weights=np.random.randn(n_inputs,n_neurons)
        self.biases=np.zeros((1,n_neurons))
        pass
    def forward(self,inputs):
        self.output=np.dot(inputs,self.weights)+self.biases
        return self.output
layer_1=Dense_Layer(3,3)
output1=layer_1.forward(X)

layer_2=Dense_Layer(3,5)
output2=layer_2.forward(output1)
print("Layer 2: ",output2)

layer_3=Dense_Layer(5,3)
output3=layer_3.forward(output2)
print("Layer 3: ",output3)

layer_4=Dense_Layer(3,1)
output4=layer_4.forward(output3)
print("Layer 4: ",output4)

Layer 2:  [[ 3.54084341e-02  1.89447854e+00  3.18022736e+00  3.33140558e+00
  -1.35826463e+00]
 [-6.26240792e-02  1.95419848e+00  2.62287619e+00  2.45772824e+00
  -1.31348602e+00]
 [-2.91006414e-01  2.87472880e+00  5.02124862e+00  3.79465742e+00
  -1.65158975e+00]
 [-4.56986093e-04  1.67000525e+00  3.31592627e+00  3.24777024e+00
  -1.13880461e+00]]
Layer 3:  [[-5.22277335  0.37541071 -0.51830169]
 [-4.09997617  0.19266464 -1.00045266]
 [-8.7915125   2.02855306 -2.09928924]
 [-5.74812592  0.89046707 -0.51635797]]
Layer 4:  [[-1.60054212]
 [-0.5035385 ]
 [-1.95916502]
 [-2.06919059]]


nn.svg