<a href="https://colab.research.google.com/github/prasannashrestha011/NeuralNetworkFromScratch/blob/main/SimpleNeuralNetwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install nnfs

In [24]:
import matplotlib as plt
import numpy as np
import nnfs

In [34]:
nnfs.init()
from nnfs.datasets import spiral_data
X,y=spiral_data(100,3)


class Dense_Layer:
    def __init__(self,n_inputs,n_neurons) -> None:
      # initializing the weights using n_inputs and n_neurons
        self.weights=np.random.randn(n_inputs,n_neurons)
        self.biases=np.zeros((1,n_neurons))
        pass
    def forward(self,inputs):
        self.output=np.dot(inputs,self.weights)+self.biases
        return self.output

class ReLu_Activation:
  def forward(self,inputs):
    self.output=np.maximum(0,inputs)
    return self.output

class SoftMax_Activation:
  def forward(self,inputs):
    exp_values=np.exp(inputs-np.max(inputs,axis=1,keepdims=True))
    probabilites=exp_values/np.sum(exp_values,axis=1,keepdims=True)
    self.output=probabilites
    return self.output


layer_1=Dense_Layer(2,3)
layer_1.forward(X)
activation=ReLu_Activation()
activation.forward(layer_1.output)

output_layer=Dense_Layer(3,3)
output_layer.forward(activation.output)

softmax=SoftMax_Activation()
output_neurons=softmax.forward(output_layer.output)

output_neurons[:5]

array([[0.33333334, 0.33333334, 0.33333334],
       [0.33173057, 0.3318284 , 0.336441  ],
       [0.3288542 , 0.3291243 , 0.3420215 ],
       [0.32587105, 0.32631534, 0.34781358],
       [0.32318372, 0.32378128, 0.35303497]], dtype=float32)

In [20]:
#softmax activation
outputs=[[1,2,3],
        [4,5,6]]
'''
exp_values=np.exp(outputs)
norm_values=exp_values/np.sum(exp_values)
'''
exp_values=np.exp(outputs)
norm_base=np.sum(outputs,axis=1,keepdims=True)
norm_values=exp_values/norm_base
print(norm_values)

np.max(outputs,axis=1,keepdims=True)


[[ 0.45304697  1.23150935  3.34758949]
 [ 3.63987667  9.89421061 26.8952529 ]]


array([[3],
       [6]])