<a href="https://colab.research.google.com/github/prasannashrestha011/NeuralNetworkFromScratch/blob/main/LogicGates.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [61]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split

## And gate ##

In [62]:
# Input tensor: 4 samples, 2 features each
X = torch.tensor([[0, 0],
                  [0, 1],
                  [1, 0],
                  [1, 1]], dtype=torch.float32)

# Output tensor: 4 samples
y = torch.tensor([[0], [0], [0], [1]], dtype=torch.float32)


In [63]:
class AND_Net(nn.Module):
    def __init__(self):
        super(AND_Net, self).__init__()
        self.fc = nn.Linear(2, 1)  # 2 inputs -> 1 output

    def forward(self, x):
        x = torch.sigmoid(self.fc(x))  # Sigmoid for binary output
        return x

model = AND_Net()


In [64]:
criterion = nn.BCELoss()        # Binary Cross Entropy
optimizer = optim.SGD(model.parameters(), lr=0.1)


In [65]:
epochs = 1000
for epoch in range(epochs):
    optimizer.zero_grad()
    outputs = model(X)
    loss = criterion(outputs, y)
    loss.backward()
    optimizer.step()

    if (epoch+1) % 100 == 0:
        print(f'Epoch {epoch+1}, Loss: {loss.item():.4f}')


Epoch 100, Loss: 0.4641
Epoch 200, Loss: 0.3638
Epoch 300, Loss: 0.3020
Epoch 400, Loss: 0.2596
Epoch 500, Loss: 0.2283
Epoch 600, Loss: 0.2040
Epoch 700, Loss: 0.1845
Epoch 800, Loss: 0.1684
Epoch 900, Loss: 0.1549
Epoch 1000, Loss: 0.1434


In [66]:
with torch.no_grad():
    outputs = model(X)
    predicted = (outputs > 0.5).float()
    print("Predicted outputs:\n", predicted)


Predicted outputs:
 tensor([[0.],
        [0.],
        [0.],
        [1.]])


##OR gate ##

In [67]:
X=torch.tensor([[0,0],
                [0,1],
                [1,0],
                [1,1]],dtype=torch.float32)
y=torch.tensor([[0],[1],[1],[1]],dtype=torch.float32)



In [68]:
class OR_NET(nn.Module):
  def __init__(self):
    super(OR_NET,self).__init__()
    self.fc=nn.Linear(2,1)
  def forward(self,x):
    x=torch.sigmoid(self.fc(x))
    return x
model=OR_NET()

In [69]:
criterion=nn.BCELoss()
optimizer=optim.SGD(params=model.parameters(),lr=0.2)


In [70]:
epochs = 1000
for epoch in range(epochs):
    optimizer.zero_grad()
    outputs = model(X)
    loss = criterion(outputs, y)
    loss.backward()
    optimizer.step()

    if (epoch+1) % 100 == 0:
        print(f'Epoch {epoch+1}, Loss: {loss.item():.4f}')


Epoch 100, Loss: 0.2372
Epoch 200, Loss: 0.1672
Epoch 300, Loss: 0.1279
Epoch 400, Loss: 0.1029
Epoch 500, Loss: 0.0857
Epoch 600, Loss: 0.0733
Epoch 700, Loss: 0.0639
Epoch 800, Loss: 0.0566
Epoch 900, Loss: 0.0507
Epoch 1000, Loss: 0.0459


In [71]:
with torch.no_grad():
  outputs=model(X)
  predicted=(outputs>0.5).float()
  print("Predicted output ",predicted)

Predicted output  tensor([[0.],
        [1.],
        [1.],
        [1.]])


## X-OR ##

x-or gate has a non linear relations.So we used one hidden layer to find the relation.
<img src="https://sdmntprwestus.oaiusercontent.com/files/00000000-3908-6230-8496-f4871559432d/raw?se=2025-09-12T04%3A37%3A15Z&sp=r&sv=2024-08-04&sr=b&scid=34658bc4-32b2-5a08-bd6d-bc4127867bcf&skoid=b64a43d9-3512-45c2-98b4-dea55d094240&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2025-09-11T21%3A58%3A52Z&ske=2025-09-12T21%3A58%3A52Z&sks=b&skv=2024-08-04&sig=dyFOb2ICT8QvydvRoPtSEUkYKWiF7yh4dZ0hkUd2i2U%3D
"
width="500"
/>

In [72]:
X=torch.tensor([[0,0],
                [0,1],
                [1,0],
                [1,1]],dtype=torch.float32)
y=torch.tensor([[0],[1],[1],[0]],dtype=torch.float32)

In [73]:
class XOR_NET(nn.Module):
  def __init__(self):
     super(XOR_NET,self).__init__()
     self.fc1=nn.Linear(2,2)
     self.fc2=nn.Linear(2,1)

  def forward(self,x):
    x=torch.sigmoid(self.fc1(x))
    x=torch.sigmoid(self.fc2(x))
    return x
model=XOR_NET()

In [77]:
criterion=nn.BCELoss()
optimizer=optim.SGD(model.parameters(),lr=0.2)


In [92]:
epochs=1000
for epoch in range(epochs):
  optimizer.zero_grad()
  output=model(X)
  loss=criterion(output,y)
  loss.backward()
  optimizer.step()

  if (epoch+1) % 100 == 0:
        print(f'Epoch {epoch+1}, Loss: {loss.item():.4f}')


Epoch 100, Loss: 0.0055
Epoch 200, Loss: 0.0055
Epoch 300, Loss: 0.0054
Epoch 400, Loss: 0.0054
Epoch 500, Loss: 0.0053
Epoch 600, Loss: 0.0052
Epoch 700, Loss: 0.0052
Epoch 800, Loss: 0.0051
Epoch 900, Loss: 0.0051
Epoch 1000, Loss: 0.0050


In [84]:
with torch.no_grad():
  output=model(X)
  predicted=(output>0.5).float()
  print("Predicted:\n ",predicted)

Predicted:
  tensor([[0.],
        [1.],
        [1.],
        [0.]])


In [94]:
X_test=torch.tensor([[1,0],[0,1],[0,0],[1,1]],dtype=torch.float32)
with torch.no_grad():
  output=model(X_test)
  predicted=(output>0.5).float()
  print("Predicted:\n ",predicted)

Predicted:
  tensor([[1.],
        [1.],
        [0.],
        [0.]])
